apiVersion: apps/v1
kind: Deployment
metadata:
  name: shalprin
  labels:
    app: shalprin
  annotations:
specs:
  selector:
    matchLabels:
      app: shalprin
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    template:
      metadata:
        labels:
          app: shalprin
      specs:
        containers:
        - name: shalprin
          image: aimvector/golang:1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort:9000
          livenessProbe:
          httpGet:
            path: /status
            port: 9000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - name: "config-volume"
            mountPath: /configs/
        volumes:
        - name: config-volume
          configMap:
            name: example-config # name of our configmap object
