apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data: 
  mariadb-root-username: dABlAHMAdAA=
  mariadb-root-password: cABhAHMAcwB3AG8AcgBkAA==
  mariadb-mysql-password: cABhAHMAcwB3AG8AcgBkAA==
          
